version: '3.9'
name: m183_lb2
services:
  db:
    image: 'mariadb:latest'
    container_name: m183-lb2-db
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      - MARIADB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql

  web:
    build: .
    container_name: m183-lb2-web
    depends_on:
      - db
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    volumes:
      - .:/var/www/html
      - php_logs:/var/log/php

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - '9200:9200'
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    environment:
      - SERVER_NAME=kibana.example.org
      - ELASTICSEARCH_HOSTS=http://elasticsearch:${ELASTICSEARCH_PORT}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    ports:
      - '${KIBANA_PORT}:${KIBANA_PORT}'
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.2
    ports:
      - '${LOGSTASH_PORT}:${LOGSTASH_PORT}'
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    depends_on:
      - elasticsearch
    environment:
      - XPACK_MONITORING_ENABLED=true
      - XPACK_MONITORING_ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME}
      - XPACK_MONITORING_ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.12.2
    volumes:
      - type: bind
        source: ./filebeat/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
        read_only: true
      - type: bind
        source: ./logs
        target: /var/www/html/logs
    command: filebeat -e -strict.perms=false
    depends_on:
      - logstash

  elastic-agent:
    image: docker.elastic.co/beats/elastic-agent:8.12.2
    depends_on:
      - elasticsearch
      - kibana
    environment:
      - FLEET_ENROLL=1
      - FLEET_ENROLL_INSECURE=1
      - FLEET_SETUP=1
      - KIBANA_HOST=http://kibana:${KIBANA_PORT}
      - ELASTICSEARCH_HOST=http://elasticsearch:${ELASTICSEARCH_PORT}
      - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - php_logs:/var/log/php

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.12.2
    user: root
    volumes:
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:${ELASTICSEARCH_PORT}
    depends_on:
      - elasticsearch
    command: metricbeat -e -system.hostfs=/hostfs

volumes:
  mariadb_data:
  es_data:
  php_logs:
