version: '3.9'
name: m183_lb2
services:
  db:
    image: 'mariadb:latest'
    container_name: m183-lb2-db
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      MARIADB_ROOT_USER: ${DATABASE_USER}
      MARIADB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_TCP_PORT: ${DATABASE_PORT}
      MYSQL_UNIX_PORT: ${DATABASE_PORT}
    volumes:
      - mariadb_data:/var/lib/mysql

  web:
    build: .
    container_name: m183-lb2-web
    depends_on:
      - db
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    volumes:
      - .:/var/www/html

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - ${ELASTICSEARCH_PORT}:${ELASTICSEARCH_PORT}
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    environment:
      - SERVER_NAME=kibana.example.org
      - ELASTICSEARCH_HOSTS=http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    ports:
      - '${KIBANA_PORT}:${KIBANA_PORT}'
    depends_on:
      - elasticsearch

volumes:
  mariadb_data:
  es_data:
