version: '3.9'
name: m183_lb2
services:
  db:
    image: 'mariadb:latest'
    container_name: m183-lb2-db
    ports:
      - '3306:3306'
    environment:
      - MARIADB_ROOT_PASSWORD=Some.Real.Secr3t
    volumes:
      - mariadb_data:/var/lib/mysql

  web:
    build: .
    container_name: m183-lb2-web
    depends_on:
      - db
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
      - php_logs:/var/log/php

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - ELASTIC_PASSWORD=elastic
    ports:
      - '9200:9200'
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    environment:
      - SERVER_NAME=kibana.example.org
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=+NaF+Di3DOetiitU_-=6
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.2
    ports:
      - '5044:5044'
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    depends_on:
      - elasticsearch
    environment:
      - XPACK_MONITORING_ENABLED=true
      - XPACK_MONITORING_ELASTICSEARCH_USERNAME=elastic
      - XPACK_MONITORING_ELASTICSEARCH_PASSWORD=elastic

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.12.2
    volumes:
      - type: bind
        source: ./filebeat/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
        read_only: true
      - type: bind
        source: ./logs
        target: /var/www/html/logs
    command: filebeat -e -strict.perms=false
    depends_on:
      - logstash

volumes:
  mariadb_data:
  es_data:
  php_logs:
