version: '3.9'
name: m183_lb2
services:
  db:
    image: 'mariadb:latest'
    container_name: m183-lb2-db
    ports:
      - '3306:3306'
    environment:
      - MARIADB_ROOT_PASSWORD=Some.Real.Secr3t
  web:
    build: .
    container_name: m183-lb2-web
    environment:
      - DBSERVER=m183-lb2-db
    ports:
      - '80:80'
    volumes:
      - type: bind
        source: /Users/jonathan/Developer/Git/TBZ/M183/todo-list
        target: /var/www/html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

